{
    'name': 'Nut Kings Ops',
    'summary': 'Offline-first inventory and distribution operations for Nut Kings',
    'version': '19.0.1.3.4',
    'category': 'Inventory/Inventory',
    'author': 'Spxcorp Limited',
    'website': 'https://spxcorp.net',
    'license': 'LGPL-3',
    'depends': ['stock', 'contacts', 'mail', 'web'],
    'data': [
        'security/roles.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/sequences.xml',
        'data/dispatch_plan_sequence.xml',
        'data/reasons.xml',
        'views/product_views.xml',
        'views/partner_views.xml',
        'views/truck_views.xml',
        'views/staff_views.xml',
        'views/reason_views.xml',
        'views/trip_views.xml',
        'views/picking_views.xml',
        'views/sync_views.xml',
        'views/physical_inventory_views.xml',
        'views/report_views.xml',
        'views/dashboard_views.xml',
        'reports/transfer_report.xml',
        'views/menus.xml',
        'views/role_service_area_views.xml',
        'views/login_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'nut_kings_ops/static/src/scss/nut_kings_backend.scss',
        ],
        'web.assets_frontend': [
            'nut_kings_ops/static/src/css/nutkings_login.css',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'application': True,
    'installable': True,
}
